RedditClone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts
end

RedditClone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RedditClone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord

  validates :title, presence: true


  belongs_to :author,
  class_name: :User,
  foreign_key: :user_id

  has_many :post_subs,
  class_name: :PostSub,
  foreign_key: :post_id
  
  has_many :subs,
  through: :post_subs,
  source: :sub
end

RedditClone/app/models/post_sub.rb
class PostSub < ApplicationRecord
  
  belongs_to :post,
  class_name: :Post,
  foreign_key: :post_id

  belongs_to :sub,
  class_name: :Sub,
  foreign_key: :sub_id

  
end

RedditClone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  user_id     :integer          not null
#  title       :string           not null
#  description :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ApplicationRecord

    validates :user_id, :title, :description, presence: true

    belongs_to :moderator,
    class_name: :User,
    foreign_key: :user_id

    has_many :posts,
    through: :post_subs,
    source: :post
end

RedditClone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord

  validates :session_token, :username, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6 }, allow_nil: true

  has_many :posts,
  class_name: :Post,
  foreign_key: :user_id

  has_many :subs,
  class_name: :Sub,
  foreign_key: :user_id

  attr_reader :password

  after_initialize :ensure_session_token

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token
    self.update!(session_token: User.generate_session_token)
    self.session_token
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return user if user && user.is_password?(password)
    nil
  end
end

RedditClone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged?, :current_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged?
    !!current_user
  end

  def ensure_logged
   redirect_to new_session_url unless logged?
  end

  def login(user)
    @current_user = user
    session[:session_token] = user.reset_session_token
  end

  def logout
    current_user.reset_session_token
    @current_user = nil
    session[:session_token] = nil
  end
end

RedditClone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def show
      @post = Post.find(params[:id])
      render :show
    end

    before_action :ensure_logged
    
    def new
      @post = Post.new
      @subs = Sub.all
      render :new
    end

    def create
      #what makes a post is a title, url, content, user_id, sub_id
      @post = Post.new(post_params)
      @post.user_id = current_user.id
      if @post.save
        redirect_to post_url(@post)
      else
        flash.now[:errors] = @post.errors.full_messages
        render :new
      end
    end

    def edit
      @post = Post.find(params[:id])
      render :edit
    end

    def update
      @post = current_user.posts.find(params[:id])
      if @post.update(post_params)
        redirect_to post_url(@post.id)
      else  
        flash.now[:errors] = @post.errors.full_messages
        render :edit
      end
    end
    
    def destroy
      @post = current_user.posts.find(params[:id])
      @post.destroy
      redirect_to sub_url(@post.sub.id)
    end

    private

    def post_params
      params.require(:post).permit(:title, :url, :content, :sub_ids)
    end
end 

RedditClone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      login(@user)
      redirect_to subs_url
    else  
      flash.now[:errors] = ["Wrong Username/Password"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end

end

RedditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  def index
    @subs = Sub.all
    render :index
  end
  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  before_action :ensure_logged

  def new
    @sub = Sub.new
    render :new
  end 
  
  def create
    #creating a new instance of sub 
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub.id)
    else   
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = current_user.subs.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub.id)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def destroy
    @sub = current_user.subs.find(params[:id])
    @sub.destroy
    redirect_to subs_url
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

end 

RedditClone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new 
    render :new
  end

  def create
    @user =  User.new(user_params)
    if @user.save
      login(@user)
      redirect_to subs_url 
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end



  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

RedditClone/app/helpers/application_helper.rb
module ApplicationHelper
end

RedditClone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<% if logged? %>
  <%= current_user.username %><br>
  <a href="<%= new_sub_url %>">Create a Sub!</a><br>
  <a href="<%= subs_url %>">All Subs</a><br>
  <form action="<%= session_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"> 
    <input type="hidden" name="_method" value="delete">
    <input type="submit" value="Sign Out">
  </form>
<% else %>
  <a href="<%= new_session_url %>">Sign In</a>
  <a href="<%= new_user_url %>">Sign Up</a>
<% end %>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %>
  <% end %>
<% end %>
  <body>
    <%= yield %>
  </body>
</html>

RedditClone/app/views/posts/new.html.erb
<%= @post.title %><br>
<%= @post.content %><br>

<form action="<%= posts_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="post[sub_ids][]">
  <% @subs.each do |sub| %> 
      <label><%= sub.title %>
      <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>"><br>
      </label>
  <% end %>
  <label>title
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>
  <label>url
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>
  <label>content
    <input type="text" name="post[content]" value="<%= @post.content %>">
  </label>
  <input type="submit" value="Make New Post">
</form>

RedditClone/app/views/posts/show.html.erb
<%= @post.title %><br>
<%= @post.content %><br>


<% @post.subs.each do |sub| %>
  <%= sub %>
<% end %>

RedditClone/app/views/subs/edit.html.erb
<h1>Edit your Sub</h1>

<form action="<%= sub_url(@sub) %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="patch">
  <label for="name">Name</label>
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  <label for="description">Description</label>
    <textarea name="sub[description]" value="<%= @sub.description %>"></textarea>
  <input type="submit" value="Submit!">
</form>

RedditClone/app/views/subs/index.html.erb
<h1>All the Subs!</h1>

<% @subs.each do |sub| %>
  <a href="<%= sub_url(sub.id) %>"><%= sub.title %></a>
<% end %>

RedditClone/app/views/subs/new.html.erb
<h1>Create Sub!</h1>

<form action="<%= subs_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="name">Name</label>
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  <label for="description">Description</label>
    <textarea name="sub[description]" value="<%= @sub.description %>"></textarea>
  <input type="submit" value="Submit!">
</form>

RedditClone/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1><br>
<h3>Description</h3><br>
<p><%= @sub.description %></p><br>
<a href="<%= new_post_url %>">Make New Post!</a><br>
<a href="<%= edit_sub_url(@sub) %>">Edit</a>

RedditClone/app/views/users/new.html.erb
<h1>Users!</h1>

<form action="<%= users_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Username
    <input type="text" name="user[username]" value="<%= @user.username %>">
  </label>
  <label>Password
    <input type="password" name="user[password]" value="">
  </label>
  <input type="submit" value="Create User">
</form>